[project]
name = "etl-watcher-sdk"
version = "0.1.41"
description = "SDK for Watcher framework"
readme = "README.md"
license = "MIT"
requires-python = ">=3.12"
dependencies = [
    "httpx[http2]>=0.28.1",
    "pydantic>=2.12.0",
    "pydantic-extra-types[pendulum]>=2.10.6",
    "pytest-xdist>=3.8.0",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.4.2",
    "ruff>=0.14.0",
    "pre-commit>=4.3.0",
]
docs = [
    "myst-parser>=4.0.1",
    "sphinx>=8.2.3",
    "sphinx-autobuild>=2025.8.25",
    "sphinx-autodoc-typehints>=3.2.0",
    "sphinx-rtd-theme>=3.0.2",
    "sphinx-tabs>=3.4.7",
    "sphinxcontrib-httpdomain>=1.8.1",
]
build = [
    "twine>=6.2.0",
    "uv-build>=0.9.0",
]
gcp = [
    "google-auth>=2.0.0",
]
azure = [
    "azure-identity>=1.0.0",
]
aws = [
    "boto3>=1.26.0",
]
cloud = [
    "google-auth>=2.0.0",
    "azure-identity>=1.0.0",
    "boto3>=1.26.0",
]

[project.urls]
Homepage = "https://github.com/cmgoffena13/etl-watcher-sdk"
Documentation = "https://etl-watcher-sdk.readthedocs.io/en/latest/"

[build-system]
requires = ["uv_build>=0.9.2,<0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "watcher"
module-root = "src"
source-exclude = ["src/watcher/tests/**", "__pycache__"]
wheel-exclude = ["src/watcher/tests/**", "__pycache__"]
